# Generated by Django 3.2.9 on 2022-04-27 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'app_animal_size',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'app_animal_type',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_board_identifier', models.CharField(max_length=20)),
                ('secret_key', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_device',
            },
        ),
        migrations.CreateModel(
            name='FeederModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app_feeder_model',
            },
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=20)),
                ('active_flag', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
            options={
                'db_table': 'app_feeding_schedule',
            },
        ),
        migrations.CreateModel(
            name='MotorTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_amount', models.FloatField(default=0)),
                ('motor_duration', models.IntegerField(default=0)),
                ('interrupter_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_motor_timing',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('weight', models.FloatField(default=0)),
                ('daily_calories_intake', models.IntegerField(default=0)),
                ('animal_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animalsize')),
                ('animal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.animaltype')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.SmallIntegerField(default=0)),
                ('time', models.TimeField(default='06:00:00')),
                ('feeding_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feedingschedule')),
                ('motor_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.motortiming')),
            ],
            options={
                'db_table': 'app_feeding_time',
            },
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet'),
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='Manual', max_length=80)),
                ('feed_type', models.CharField(choices=[('M', 'Manual'), ('S', 'Scheduled')], default='M', max_length=1)),
                ('feed_amt', models.CharField(default='1/4 cup', max_length=12)),
                ('feed_timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
            options={
                'db_table': 'app_feeding_log',
            },
        ),
        migrations.CreateModel(
            name='EventQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
            options={
                'db_table': 'app_event_queue',
            },
        ),
        migrations.CreateModel(
            name='DeviceOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_device_owner',
            },
        ),
    ]
