# Generated by Django 4.0.4 on 2022-05-22 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'app_animal_size',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'app_animal_type',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Article categories',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=255)),
                ('slide_label', models.CharField(max_length=128)),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_board_identifier', models.CharField(max_length=20)),
                ('secret_key', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Feeder', max_length=50)),
                ('device_key', models.CharField(default='Key is not set', max_length=32)),
                ('manual_button', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
            options={
                'db_table': 'app_device_owner',
            },
        ),
        migrations.CreateModel(
            name='FeederModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=255)),
                ('hopper_capacity', models.FloatField(default=20)),
                ('has_hopper_sensor', models.BooleanField(default=True)),
                ('has_motor_sensor', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_feeder_model',
            },
        ),
        migrations.CreateModel(
            name='MotorTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_amount', models.FloatField(default=0)),
                ('motor_duration', models.IntegerField(default=0)),
                ('interrupter_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_motor_timing',
            },
        ),
        migrations.CreateModel(
            name='PosixTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=50)),
                ('posix_tz', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_posix_timezone',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('weight', models.FloatField(default=0)),
                ('daily_calories_intake', models.IntegerField(default=0)),
                ('animal_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animalsize')),
                ('animal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.animaltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushover_user_key', models.CharField(default=None, max_length=32)),
                ('pushover_devices', models.JSONField(default=None, max_length=2048)),
                ('auto_food', models.BooleanField(default=False)),
                ('manual_food', models.BooleanField(default=False)),
                ('feeder_offline', models.BooleanField(default=False)),
                ('low_hopper', models.BooleanField(default=False)),
                ('power_disconnected', models.BooleanField(default=False)),
                ('low_battery', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('E', 'Error')], default='P', max_length=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.deviceowner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=20)),
                ('active_flag', models.BooleanField(default=True)),
                ('dow', models.SmallIntegerField(default=0)),
                ('time', models.TimeField(default='06:00:00')),
                ('local_time', models.TimeField(default='06:00:00')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
                ('device_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deviceowner')),
                ('motor_timing', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.motortiming')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet')),
            ],
            options={
                'db_table': 'app_feeding_schedule',
            },
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='Manual', max_length=80)),
                ('feed_type', models.CharField(choices=[('M', 'Manual'), ('S', 'Scheduled'), ('R', 'Remote')], default='M', max_length=1)),
                ('feed_amt', models.FloatField(default=0.5)),
                ('feed_timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deviceowner')),
            ],
            options={
                'db_table': 'app_feeding_log',
            },
        ),
        migrations.CreateModel(
            name='EventQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.IntegerField(null=True)),
                ('json_payload', models.JSONField(max_length=1024, null=True)),
                ('status_code', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deviceowner')),
            ],
            options={
                'db_table': 'app_event_queue',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_boot', models.DateTimeField(auto_now_add=True)),
                ('last_ping', models.DateTimeField(auto_now_add=True)),
                ('battery_voltage', models.FloatField(default=0.0, null=True)),
                ('battery_soc', models.FloatField(default=0.0, null=True)),
                ('battery_crate', models.FloatField(default=0.0, null=True)),
                ('hopper_level', models.FloatField(default=0.0, null=True)),
                ('has_event', models.BooleanField(default=False)),
                ('on_power', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
            options={
                'db_table': 'app_device_status',
            },
        ),
        migrations.AddField(
            model_name='deviceowner',
            name='feeder_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.feedermodel'),
        ),
        migrations.AddField(
            model_name='deviceowner',
            name='manual_motor_timing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.motortiming'),
        ),
        migrations.AddField(
            model_name='deviceowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Article Title', max_length=256)),
                ('display_title', models.CharField(blank=True, max_length=128, null=True)),
                ('author', models.CharField(default='Anonymous', max_length=64)),
                ('content', models.TextField(default='Need content')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articlecategory')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
