# Generated by Django 3.2.9 on 2022-05-01 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventqueue',
            name='event_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventqueue',
            name='value',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('battery_soc', models.FloatField(null=True)),
                ('hopper_level', models.FloatField(null=True)),
                ('has_event', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
            options={
                'db_table': 'app_device_status',
            },
        ),
    ]
