# Generated by Django 4.0.4 on 2022-05-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.animalsize'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(default='Unnamed Pet', max_length=25),
        ),
    ]
