# Generated by Django 3.2.9 on 2022-05-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220501_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceowner',
            name='auth_key',
            field=models.CharField(default='Key is not set', max_length=32),
        ),
        migrations.AddField(
            model_name='deviceowner',
            name='name',
            field=models.CharField(default='Unnamed Feeder', max_length=50),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='last_boot',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
