# Generated by Django 3.2.9 on 2022-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220502_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceowner',
            old_name='auth_key',
            new_name='device_key',
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='last_boot',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
