# Generated by Django 4.0.4 on 2022-05-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pet_animal_size_alter_pet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlBoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('revision', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.controlboardmodel')),
            ],
        ),
    ]
