# Generated by Django 3.2.9 on 2022-05-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220504_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventqueue',
            name='device',
        ),
        migrations.AddField(
            model_name='eventqueue',
            name='device_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.deviceowner'),
            preserve_default=False,
        ),
    ]
