# Generated by Django 4.0.4 on 2022-05-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_devicestatus_firmware_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='control_board_version',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
