# Generated by Django 3.2.9 on 2022-05-04 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220504_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventqueue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
