# Generated by Django 3.2.9 on 2022-05-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_eventqueue_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='battery_voltage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='on_power',
            field=models.BooleanField(default=True),
        ),
    ]
