# Generated by Django 4.0.4 on 2022-05-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_devicestatus_control_board_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlboardmodel',
            name='revision',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='control_board_version',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
