# Generated by Django 4.0.4 on 2022-05-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_controlboardmodel_revision_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicestatus',
            old_name='control_board_version',
            new_name='control_board_revision',
        ),
    ]
