# Generated by Django 3.2.9 on 2022-05-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220504_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventqueue',
            name='status_code',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='eventqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
