# Generated by Django 4.0.4 on 2022-05-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_firmwareupdate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='firmware_version',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdate',
            name='version',
            field=models.CharField(max_length=15),
        ),
    ]
