# Generated by Django 3.2.9 on 2022-05-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220507_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinglog',
            name='feed_amt',
            field=models.FloatField(default=0.5),
        ),
    ]
