# Generated by Django 3.2.9 on 2022-05-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_feedinglog_feed_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventqueue',
            name='value',
        ),
        migrations.AddField(
            model_name='eventqueue',
            name='json_payload',
            field=models.JSONField(max_length=1024, null=True),
        ),
    ]
