# Generated by Django 4.0.4 on 2022-05-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_devicestatus_firmware_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='firmware_version',
            field=models.CharField(default='factory', max_length=15, null=True),
        ),
    ]
