# Generated by Django 3.2.9 on 2022-05-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220507_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventqueue',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
