# Generated by Django 3.2.9 on 2022-05-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_date_created_eventqueue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinglog',
            name='feed_type',
            field=models.CharField(choices=[('M', 'Manual'), ('S', 'Scheduled'), ('R', 'Remote')], default='M', max_length=1),
        ),
    ]
