# Generated by Django 4.0.4 on 2022-06-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_devicestatus_is_hopper_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='caption',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
