# Generated by Django 3.2.9 on 2022-05-12 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_feedinglog_feed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceowner',
            name='feeder_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.feedermodel'),
        ),
    ]
