# Generated by Django 4.0.4 on 2022-06-17 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_carousel_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinglog',
            name='feed_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
