# Generated by Django 3.2.9 on 2022-05-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_deviceowner_feeder_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosixTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=50)),
                ('posix_tz', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_posix_timezone',
            },
        ),
    ]
