# Generated by Django 3.2.9 on 2022-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_posixtimezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='battery_crate',
            field=models.FloatField(null=True),
        ),
    ]
