# Generated by Django 3.2.9 on 2022-05-16 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_devicestatus_battery_crate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushover_user_key', models.CharField(default=None, max_length=32)),
                ('pushover_devices', models.JSONField(default=None, max_length=2048)),
                ('auto_food', models.BooleanField(default=False)),
                ('manual_food', models.BooleanField(default=False)),
                ('feeder_offline', models.BooleanField(default=False)),
                ('low_hopper', models.BooleanField(default=False)),
                ('power_disconnected', models.BooleanField(default=False)),
                ('low_battery', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], default='P', max_length=1)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deviceowner')),
            ],
        ),
    ]
