# Generated by Django 3.2.9 on 2022-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_messagequeue_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedermodel',
            name='hopper_capacity',
            field=models.FloatField(default=20),
        ),
    ]
