# Generated by Django 3.2.9 on 2022-05-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_deviceowner_manual_portion_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceowner',
            name='manual_portion_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.motortiming'),
        ),
    ]
