# Generated by Django 3.2.9 on 2022-05-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_deviceowner_manual_portion_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceowner',
            old_name='manual_portion_size',
            new_name='manual_motor_timing',
        ),
    ]
