# Generated by Django 3.2.9 on 2022-05-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_article_articlecategory_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Untitled Article Title', max_length=256),
        ),
    ]
