# Generated by Django 3.2.9 on 2022-05-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
