# Generated by Django 3.2.9 on 2022-05-17 22:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_article_display_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 22, 58, 56, 836907, tzinfo=utc)),
        ),
    ]
