# Generated by Django 3.2.9 on 2022-05-18 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220517_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-is_pinned', '-published_at']},
        ),
        migrations.AddField(
            model_name='deviceowner',
            name='manual_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
