# Generated by Django 3.2.9 on 2022-05-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220518_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name_plural': 'Article categories'},
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='dow',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='motor_timing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.motortiming'),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='time',
            field=models.TimeField(default='06:00:00'),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='battery_crate',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='battery_soc',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='battery_voltage',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='hopper_level',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='FeedingTime',
        ),
    ]
