# Generated by Django 3.2.13 on 2022-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_feedingschedule_device_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingschedule',
            name='local_time',
            field=models.TimeField(default='06:00:00'),
        ),
    ]
