# Generated by Django 3.2.13 on 2022-05-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_feedingschedule_local_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedermodel',
            name='has_hopper_sensor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedermodel',
            name='has_motor_sensor',
            field=models.BooleanField(default=True),
        ),
    ]
