# Generated by Django 4.0.4 on 2022-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220519_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagequeue',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='status_code',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('E', 'Error')], default='P', max_length=1),
        ),
    ]
