# Generated by Django 4.0.4 on 2022-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_messagequeue_title_alter_messagequeue_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagequeue',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
