# Generated by Django 4.0.4 on 2022-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_messagequeue_user_alter_messagequeue_device_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='last_ping',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
